# Generated by Django 2.0 on 2017-12-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=700),
        ),
    ]
