# Generated by Django 2.0 on 2017-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171224_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='serialno',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
