# Generated by Django 2.0 on 2017-12-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171224_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logout',
            field=models.IntegerField(default=0),
        ),
    ]
